[package]
authors = ["Adriano Moreira"]
name = "euler-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"

[[bin]]
name = "euler001"
path = "src/problem001.rs"

[[bin]]
name = "euler002"
path = "src/problem002.rs"
